### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by frontyard** [pejonic/cordova-pejonic-plugin-exoplayer#4]
I'm the maintainer of the original version of this plugin: https://github.com/frontyard/cordova-plugin-exoplayer

It would be great if we focused both of our energies on a single copy of the plugin through forks and pull requests. That way we all benefit from combined efforts. Just a thought.

**Comment by johnnwanosike1** [comment]
That will be great, but I will look at it. I planned doing 360 view feature
for it. Thanks

On Mar 27, 2018 10:02 AM, "Nedim Cholich" <notifications@github.com> wrote:

I'm the maintainer of the original version of this plugin:
https://github.com/frontyard/cordova-plugin-exoplayer

It would be great if we focused both of our energies on a single copy of
the plugin through forks and pull requests. That way we all benefit from
combined efforts. Just a thought.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pejonic/cordova-pejonic-plugin-exoplayer/issues/4>, or mute
the thread
